port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

proxies:
  - name: "trojan-os-2"
    type: trojan
    server: os-2.rise-fuji.com
    port: 443
    password: t3sOyCH7nAiHOFU5Mt
    udp: true
    sni: os-2.rise-fuji.com
    skip-cert-verify: false

proxy-groups:
  - name: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
    type: select
    proxies:
      - trojan-os-2
      - DIRECT

  - name: "ğŸŒ å›½å¤–æµé‡"
    type: select
    proxies:
      - trojan-os-2
      - DIRECT

  - name: "ğŸ“º æµåª’ä½“"
    type: select
    proxies:
      - trojan-os-2
      - DIRECT

rules:
  - DOMAIN-SUFFIX,google.com,ğŸŒ å›½å¤–æµé‡
  - DOMAIN-SUFFIX,youtube.com,ğŸ“º æµåª’ä½“
  - DOMAIN-SUFFIX,github.com,ğŸŒ å›½å¤–æµé‡
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
