echo "# clash-config" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/chrisansder/clash-config.git
git push -u origin main
